version: '3.8'

services:
  # MongoDB para desenvolvimento
  mongodb:
    image: mongo:7.0
    container_name: campaign-watch-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - campaign-watch-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ para desenvolvimento
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: campaign-watch-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - campaign-watch-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  # Vault para desenvolvimento
  vault:
    image: vault:1.15
    container_name: campaign-watch-vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    networks:
      - campaign-watch-network
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Consul para desenvolvimento
  consul:
    image: consul:1.17
    container_name: campaign-watch-consul
    restart: unless-stopped
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: agent -server -ui -bootstrap-expect=1 -client=0.0.0.0
    volumes:
      - consul_data:/consul/data
    networks:
      - campaign-watch-network
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Worker - Comentado por padrão para desenvolvimento local
  # campaign-watch-worker:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: campaign-watch-worker
  #   restart: unless-stopped
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - CONN_STRING_VAULT=http://vault:8200
  #     - USER_VAULT=monitoring-dev
  #     - PASS_VAULT=monitoring-dev
  #     - TENANT=6445d693b443206381ab91c2
  #     - PathLog=/var/logs
  #   volumes:
  #     - ./logs:/var/logs
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #     vault:
  #       condition: service_healthy
  #     consul:
  #       condition: service_healthy
  #   networks:
  #     - campaign-watch-network

volumes:
  mongodb_data:
    driver: local
  rabbitmq_data:
    driver: local
  consul_data:
    driver: local

networks:
  campaign-watch-network:
    driver: bridge